routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ExampleController;
use App\Http\Controllers\Backend\VisiController;
use App\Http\Controllers\Backend\AboutController;
use App\Http\Controllers\Backend\BannerController;
use App\Http\Controllers\Backend\DashboardController;
use App\Http\Controllers\Backend\PreferenceController;
use App\Http\Controllers\Backend\AbouttController;
use App\Http\Controllers\Backend\Quote1Controller;
use App\Http\Controllers\Backend\HeaderController;
use App\Http\Controllers\Backend\Quote2Controller;
use App\Http\Controllers\Backend\ContactController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', [ExampleController::class, 'index']);

Route::group(['namespace' => 'App\Http\Controllers\Backend', 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Auth::routes();
    Route::middleware('auth:web')->group(function () {

        Route::get('/', [DashboardController::class, 'index'])->name('dashboard');

        Route::group(['prefix' => 'banner', 'as' => 'banner.'], function () {
            Route::get('/', [BannerController::class, 'index'])->name('index');
            Route::get('/create', [BannerController::class, 'create'])->name('create');
            Route::post('/store', [BannerController::class, 'store'])->name('store');
            Route::get('edit/{banner}', [BannerController::class, 'edit'])->name('edit');
            Route::post('/update/{banner}', [BannerController::class, 'update'])->name('update');
            Route::get('delete/{banner}', [BannerController::class, 'delete'])->name('delete');
        });

        // Route::group(['prefix' => 'about', 'as' => 'about.'], function () {
        //     Route::get('/', [AboutController::class, 'index'])->name('index');
        //     Route::post('/store', [AboutController::class, 'store'])->name('store');
        //     Route::post('/update/{content}', [AboutController::class, 'update'])->name('update');
        // });

        Route::group(['prefix' => 'menu', 'as' => 'menu.'], function () {
            Route::get('/', [VisiController::class, 'index'])->name('index');
            Route::get('/create', [VisiController::class, 'create'])->name('create');
            Route::post('/store', [VisiController::class, 'store'])->name('store');
            Route::get('edit/{menu}', [VisiController::class, 'edit'])->name('edit');
            Route::post('/update/{menu}', [VisiController::class, 'update'])->name('update');
            Route::get('delete/{menu}', [VisiController::class, 'delete'])->name('delete');
        });

        Route::group(['prefix' => 'aboutt', 'as' => 'aboutt.'], function () {
            Route::get('/', [AbouttController::class, 'index'])->name('index');
            Route::post('/update/{aboutt}', [AbouttController::class, 'update'])->name('update');
        });

        Route::group(['prefix' => 'quote1', 'as' => 'quote1.'], function () {
            Route::get('/', [Quote1Controller::class, 'index'])->name('index');
            Route::post('/update/{quote1}', [Quote1Controller::class, 'update'])->name('update');
        });

        Route::group(['prefix' => 'header', 'as' => 'header.'], function () {
            Route::get('/', [HeaderController::class, 'index'])->name('index');
            Route::post('/update/{header}', [HeaderController::class, 'update'])->name('update');
        });

        Route::group(['prefix' => 'quote2', 'as' => 'quote2.'], function () {
            Route::get('/', [Quote2Controller::class, 'index'])->name('index');
            Route::post('/update/{quote2}', [Quote2Controller::class, 'update'])->name('update');
        });

        Route::group(['prefix' => 'contact', 'as' => 'contact.'], function () {
            Route::get('/', [ContactController::class, 'index'])->name('index');
            Route::post('/update/{contact}', [ContactController::class, 'update'])->name('update');
        });
    });
});

app/Http/Controllers/Backend/AbouttController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Repository\UploadRepository;
use App\Models\Preference;


class AbouttController extends Controller
{
    protected $upload;
    public function __construct(UploadRepository $upload)
    {
        $this->upload = $upload;
    }

    public function index()
    {
        $data = Preference::where('type', 'aboutt')->first();
        // return $data->Atribute['title'];
        return view('backend.pages.aboutt.index', compact('data'));
    }

    public function update(Request $request, $id)
    {
        $preference = Preference::where('id', $id)->first();
        $request->validate([
            'image'          => 'mimes:jpg,png,jpeg,svg|max:1000',
            'title'          => 'required',
            'description'    => 'required',
            'sub'            => 'required',
        ]);

        if ($request->file('image')) {
            $image = $this->upload->update($preference->image, $request->file('image'));
        } else {
            $image = $preference->image;
        }

        $preference->update([
            'type'      => 'aboutt',
            'Atribute' => [
                'image' => $image, // Use the updated image variable here
                'title' => $request->title,
                'description' => $request->description,
                'sub' => $request->sub,
            ]
        ]);

        return redirect()->route('admin.aboutt.index')->with(['updated' => 'updated']);
    }
}

resources/views/backend/pages/aboutt/index.blade.php
@extends('backend.layouts.app')
@section('content')
    <link rel="stylesheet" type="text/css" href="/backend/app-assets/css/core/menu/menu-types/vertical-menu.css">
    <link rel="stylesheet" type="text/css" href="/backend/app-assets/css/plugins/forms/pickers/form-flat-pickr.css">
    <link rel="stylesheet" type="text/css" href="/backend/app-assets/css/plugins/forms/pickers/form-pickadate.css">
    <link rel="stylesheet" href="/backend/app-assets/css/uploader.css">
    <link rel="stylesheet" href="/backend/app-assets/css/uploader-2.css">

    <div class="content-header row">
        <div class="content-header-left col-md-9 col-12 mb-2">
            <div class="row breadcrumbs-top">
                <div class="col-12">
                    <div class="breadcrumb-wrapper">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="/admin">Dashboard</a>
                            </li>
                            <li class="breadcrumb-item active">
                                Aboutt
                            </li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="content-body">
        <!-- Validation -->
        <section class="bs-validation">
            @if ($data !== null)
                <form action="{{ route('admin.aboutt.update', $data->id) }}" method="POST" enctype="multipart/form-data">
            @endif
            @csrf
            <div class="row">
                <!-- Bootstrap Validation -->
                <div class="col-md-12 col-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">Aboutt</h4>
                        </div>
                        <div class="card-body">
                            <div class="form-group">
                                <label class="form-label" for="basic-addon-name">Title</label>
                                <input type="text" id="basic-addon-name" name="title"
                                    class="form-control @error('title') border-danger @enderror" aria-label="title"
                                    value="{{ $data && isset($data->Atribute['title']) ? $data->Atribute['title'] : '' }}"
                                    aria-describedby="basic-addon-title" />
                                @error('title')
                                    <span class="text-danger">*{{ $message }}</span>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label class="form-label" for="basic-addon-name">Description</label>
                                <textarea name="description" id="descriptions" cols="30" rows="10"
                                    class="form-control @error('description') border-danger @enderror">{{ $data && isset($data->Atribute['description']) ? $data->Atribute['description'] : '' }}</textarea>
                                @error('description')
                                    <span class="text-danger">*{{ $message }}</span>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label class="form-label" for="basic-addon-name">Sub</label>
                                <input type="text" id="basic-addon-name" name="sub"
                                    class="form-control @error('sub') border-danger @enderror" aria-label="sub"
                                    value="{{ $data && isset($data->Atribute['sub']) ? $data->Atribute['sub'] : '' }}"
                                    aria-describedby="basic-addon-button_name" />
                                @error('sub')
                                    <span class="text-danger">*{{ $message }}</span>
                                @enderror
                            </div>

                            <div class="file-upload  @error('image') border-danger @enderror">
                                <button class="file-upload-btn" type="button"
                                    onclick="$('.file-upload-input').trigger( 'click' )">Add image</button>
                                <div class="image-upload-wrap">
                                    <input class="file-upload-input" type='file' onchange="readURL(this);"
                                        accept="image/*" name="image" />
                                    <div class="drag-text">
                                        @if ($data !== null)
                                            <img class="file-upload-image"
                                                src="{{ $data && isset($data->Atribute['image']) ? $data->Atribute['image'] : '' }}"
                                                alt="your image" />
                                        @else
                                            <h3>Drag and drop a file or select add image</h3>
                                        @endif
                                    </div>
                                </div>
                                <div class="file-upload-content">
                                    <img class="file-upload-image" src="" alt="your image" />
                                    <div class="image-title-wrap">
                                        <button type="button" onclick="removeUpload()" class="remove-image">Remove <span
                                                class="image-title">Uploaded image</span></button>
                                    </div>
                                </div>
                                <small class="text-danger">** Max 1mb</small> <br>
                                @error('image')
                                    <span class="text-danger">*{{ $message }}</span>
                                @enderror
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row mb-4">
                <div class="col-md-6">
                    <button data-loading-text="Loading ..." type="submit" class="btn btn-primary">Save Changes</button>
                </div>
            </div>
            </form>
        </section>
    </div>
@endsection

@section('script')
    <script src="https://cdn.ckeditor.com/4.16.1/standard/ckeditor.js"></script>
    @if (session('created'))
        <script>
            $(function() {
                toastr['success']('👋 Yes Data Created !!.', 'Created Success', {
                    closeButton: true,
                    tapToDismiss: false,
                    progressBar: true,
                });
            });
        </script>
    @elseif(session('updated'))
        <script>
            $(function() {
                toastr['success']('👋 Yes Data Updated !!.', 'Updated Success', {
                    closeButton: true,
                    tapToDismiss: false,
                    progressBar: true,
                });
            });
        </script>
    @endif
    <script>
        $(function() {
            var textarea = document.getElementById('descriptions');
            CKEDITOR.replace(textarea);

            var vision = document.getElementById('vision');
            CKEDITOR.replace(vision);

            var mission = document.getElementById('mission');
            CKEDITOR.replace(mission);

            var our_values = document.getElementById('our_value');
            CKEDITOR.replace(our_values);

            var description = document.getElementById('description_1');
            CKEDITOR.replace(description);

            var description_2 = document.getElementById('description_2');
            CKEDITOR.replace(description_2);
        });
    </script>
    <script>
        function readURL(input) {
            if (input.files && input.files[0]) {

                var reader = new FileReader();

                reader.onload = function(e) {
                    $('.image-upload-wrap').hide();

                    $('.file-upload-image').attr('src', e.target.result);
                    $('.file-upload-content').show();

                    $('.image-title').html(input.files[0].name);
                };

                reader.readAsDataURL(input.files[0]);

            } else {
                removeUpload();
            }
        }

        function removeUpload() {
            $('.file-upload-input').replaceWith($('.file-upload-input').clone());
            $('.file-upload-content').hide();
            $('.image-upload-wrap').show();
        }

        $(function() {
            $('.image-upload-wrap').bind('dragover', function() {
                $('.image-upload-wrap').addClass('image-dropping');
            });

            $('.image-upload-wrap').bind('dragleave', function() {
                $('.image-upload-wrap').removeClass('image-dropping');
            });
        });

        function readURL2(input) {
            if (input.files && input.files[0]) {

                var reader = new FileReader();

                reader.onload = function(e) {
                    $('.image-upload-wrap-2').hide();

                    $('.file-upload-image-2').attr('src', e.target.result);
                    $('.file-upload-content-2').show();

                    $('.image-title-2').html(input.files[0].name);
                };

                reader.readAsDataURL(input.files[0]);

            } else {
                removeUpload2();
            }
        }

        function removeUpload2() {
            $('.file-upload-input-2').replaceWith($('.file-upload-input-2').clone());
            $('.file-upload-content-2').hide();
            $('.image-upload-wrap-2').show();
        }

        $(function() {
            $('.image-upload-wrap-2').bind('dragover', function() {
                $('.image-upload-wrap-2').addClass('image-dropping-2');
            });

            $('.image-upload-wrap-2').bind('dragleave', function() {
                $('.image-upload-wrap-2').removeClass('image-dropping-2');
            });
        });
    </script>
@endsection