routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ExampleController;
use App\Http\Controllers\Backend\VisiController;
use App\Http\Controllers\Backend\AboutController;
use App\Http\Controllers\Backend\BannerController;
use App\Http\Controllers\Backend\DashboardController;
use App\Http\Controllers\Backend\PreferenceController;
use App\Http\Controllers\Backend\AbouttController;
use App\Http\Controllers\Backend\Quote1Controller;
use App\Http\Controllers\Backend\HeaderController;
use App\Http\Controllers\Backend\Quote2Controller;
use App\Http\Controllers\Backend\ContactController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', [ExampleController::class, 'index']);

Route::group(['namespace' => 'App\Http\Controllers\Backend', 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Auth::routes();
    Route::middleware('auth:web')->group(function () {

        Route::get('/', [DashboardController::class, 'index'])->name('dashboard');

        Route::group(['prefix' => 'banner', 'as' => 'banner.'], function () {
            Route::get('/', [BannerController::class, 'index'])->name('index');
            Route::get('/create', [BannerController::class, 'create'])->name('create');
            Route::post('/store', [BannerController::class, 'store'])->name('store');
            Route::get('edit/{banner}', [BannerController::class, 'edit'])->name('edit');
            Route::post('/update/{banner}', [BannerController::class, 'update'])->name('update');
            Route::get('delete/{banner}', [BannerController::class, 'delete'])->name('delete');
        });

        // Route::group(['prefix' => 'about', 'as' => 'about.'], function () {
        //     Route::get('/', [AboutController::class, 'index'])->name('index');
        //     Route::post('/store', [AboutController::class, 'store'])->name('store');
        //     Route::post('/update/{content}', [AboutController::class, 'update'])->name('update');
        // });

        Route::group(['prefix' => 'menu', 'as' => 'menu.'], function () {
            Route::get('/', [VisiController::class, 'index'])->name('index');
            Route::get('/create', [VisiController::class, 'create'])->name('create');
            Route::post('/store', [VisiController::class, 'store'])->name('store');
            Route::get('edit/{menu}', [VisiController::class, 'edit'])->name('edit');
            Route::post('/update/{menu}', [VisiController::class, 'update'])->name('update');
            Route::get('delete/{menu}', [VisiController::class, 'delete'])->name('delete');
        });

        Route::group(['prefix' => 'aboutt', 'as' => 'aboutt.'], function () {
            Route::get('/', [AbouttController::class, 'index'])->name('index');
            Route::post('/update/{aboutt}', [AbouttController::class, 'update'])->name('update');
        });

        Route::group(['prefix' => 'quote1', 'as' => 'quote1.'], function () {
            Route::get('/', [Quote1Controller::class, 'index'])->name('index');
            Route::post('/update/{quote1}', [Quote1Controller::class, 'update'])->name('update');
        });

        Route::group(['prefix' => 'header', 'as' => 'header.'], function () {
            Route::get('/', [HeaderController::class, 'index'])->name('index');
            Route::post('/update/{header}', [HeaderController::class, 'update'])->name('update');
        });

        Route::group(['prefix' => 'quote2', 'as' => 'quote2.'], function () {
            Route::get('/', [Quote2Controller::class, 'index'])->name('index');
            Route::post('/update/{quote2}', [Quote2Controller::class, 'update'])->name('update');
        });

        Route::group(['prefix' => 'contact', 'as' => 'contact.'], function () {
            Route::get('/', [ContactController::class, 'index'])->name('index');
            Route::post('/update/{contact}', [ContactController::class, 'update'])->name('update');
        });
    });
});

app/Models/Banner.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Banner extends Model
{
    use HasFactory;

    protected $guarded = [];
}

app/Http/Controllers/Backend/BannerController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Models\Banner;
use Illuminate\Http\Request;
use Yajra\DataTables\DataTables;
use App\Http\Controllers\Controller;
use App\Repository\UploadRepository;

class BannerController extends Controller
{
    protected $upload;
    public function __construct(UploadRepository $upload) {
        $this->upload = $upload;
    }
    
    public function index()
    {
        if(request()->ajax()){
            $data = Banner::latest()->get();
            return DataTables::of($data)->make(true);
        }

        return view('backend.pages.banner.index');
    }

    public function create()
    {
        $data = null;
        return view('backend.pages.banner.action', compact('data'));
    }

    public function store(Request $request)
    {
        request()->validate([
            'image'             => 'mimes:jpg,png,jpeg|max:3000',
        ]);

        if($request->file('image')){
            $image  = $this->upload->save($request->file('image'));
        }else{
            $image  = null;
        }
        
        Banner::create([
            'image'            => $image,
        ]);

        return redirect()->route('admin.banner.index')->with(['created' => 'created']);
    }

    public function edit(Banner $banner)
    {
        $data = $banner;

        return view('backend.pages.banner.action', compact('data'));
    }

    public function update(Request $request , Banner $banner)
    {
        request()->validate([
            'image'             => 'mimes:jpg,png,jpeg|max:3000',
        ]);

        if($request->file('image')){
            $image = $this->upload->update($banner->image,$request->file('image'));
        }else{
            $image = $banner->image;
        }
        
        $banner->update([
            'image'            => $image,
        ]);

        return redirect()->route('admin.banner.index')->with(['updated' => 'updated']);
    }

    public function delete(Banner $banner)
    {
        $this->upload->delete($banner->image);

        $banner->delete();
    }
}

resources/views/backend/pages/banner/action.blade.php
@extends('backend.layouts.app')
@section('content')
<div class="content-header row">
    <div class="content-header-left col-md-9 col-12 mb-2">
        <div class="row breadcrumbs-top">
            <div class="col-12">
                <div class="breadcrumb-wrapper">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Home</a>
                        </li>
                        <li class="breadcrumb-item"><a href="#">Banner</a>
                        </li>
                        <li class="breadcrumb-item active">
                            @if ($data == null)
                            Create Banner
                            @else
                            Update Banner
                            @endif
                        </li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="content-body">

    <!-- Validation -->
    <section class="bs-validation">
        @if ($data !== null)
        <form action="{{ route('admin.banner.update', $data->id) }}" method="POST" enctype="multipart/form-data">    
        @else
        <form action="{{ route('admin.banner.store') }}" id="jquery-val-form" method="POST" enctype="multipart/form-data">
        @endif
        @csrf
            <div class="row">
                <!-- Bootstrap Validation -->
                <div class="col-md-12 col-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">
                                @if ($data == null)
                                Create Banner
                                @else
                                Update Banner
                                @endif
                            </h4>
                        </div>
                        <div class="card-body">
                            <div class="file-upload  @error('image') border-danger @enderror">
                                <button class="file-upload-btn" type="button" onclick="$('.file-upload-input').trigger( 'click' )">Add image</button>
                                <div class="image-upload-wrap">
                                    <input class="file-upload-input" type='file' onchange="readURL(this);" accept="image/*" name="image" />
                                    <div class="drag-text">
                                        @if ($data !== null)
                                            <img class="file-upload-image" src="{{ $data->image }}" alt="your image" />
                                        @else
                                            <h3>Drag and drop a file or select add image banner</h3>
                                        @endif
                                    </div>
                                </div>
                                <div class="file-upload-content">
                                    <img class="file-upload-image" src="" alt="your image" />
                                    <div class="image-title-wrap">
                                        <button type="button" onclick="removeUpload()" class="remove-image">Remove <span class="image-title">Uploaded image</span></button>
                                    </div>
                                </div>
                                <small class="text-danger">** Max 2mb</small> <br>
                                @error('image')
                                    <span class="text-danger">*{{ $message }}</span>
                                @enderror
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row mb-4">
                <div class="col-md-6">
                    <button type="submit"
                    data-initial-text="Update <i class='icon-paperplane ml-2'></i>"
                    data-loading-text="<i class='fas fa-spinner fa-spin'></i> Loading..."
                    class="btn btn-primary"> Save Changes </button>
                </div>
            </div>
        </form>
    </section>
</div>

@endsection

@section('script')
<script>
    function readURL(input) {
        if (input.files && input.files[0]) {

            var reader = new FileReader();

            reader.onload = function(e) {
            $('.image-upload-wrap').hide();

            $('.file-upload-image').attr('src', e.target.result);
            $('.file-upload-content').show();

            $('.image-title').html(input.files[0].name);
            };

            reader.readAsDataURL(input.files[0]);

        } else {
            removeUpload();
        }
    }

    function removeUpload() {
        $('.file-upload-input').replaceWith($('.file-upload-input').clone());
        $('.file-upload-content').hide();
        $('.image-upload-wrap').show();
    }

    $(function (){
        $('.image-upload-wrap').bind('dragover', function () {
            $('.image-upload-wrap').addClass('image-dropping');
        });

        $('.image-upload-wrap').bind('dragleave', function () {
                $('.image-upload-wrap').removeClass('image-dropping');
        });
    });

</script>
@if(Session::get('create'))
    <script type="text/javascript">
        $(document).ready(function(){

            // Success Type
        toastr['success']('Successfully Create Data.', 'Successfully', {
            closeButton: true,
            tapToDismiss: false,
            progressBar: true,
        });

    });
</script>
@endif

@if(Session::get('update'))
<script type="text/javascript">
    $(document).ready(function(){

        // Success Type
        toastr['success']('Successfully Update Data.', 'Successfully', {
            closeButton: true,
            tapToDismiss: false,
            progressBar: true,
        });

    });
</script>
@endif
@endsection

resources/views/backend/pages/banner/index.blade.php
@extends('backend.layouts.app')
@section('content')

<link rel="stylesheet" type="text/css" href="/backend/backend/app-assets/css/core/menu/menu-types/vertical-menu.css">
<link rel="stylesheet" type="text/css" href="/backend/backend/app-assets/css/plugins/forms/pickers/form-flat-pickr.css">
<link rel="stylesheet" type="text/css" href="/backend/backend/app-assets/css/plugins/forms/pickers/form-pickadate.css">

<div class="content-header row">
    <div class="content-header-left col-md-9 col-12 mb-2">
        <div class="row breadcrumbs-top">
            <div class="col-12">
                <div class="breadcrumb-wrapper">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Home</a>
                        </li>
                        <li class="breadcrumb-item"><a href="#">Banner</a>
                        </li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
</div>
    <div class="content-body">
        <!-- Basic table -->
        <section id="ajax-datatable">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header border-bottom">
                            <h4 class="card-title">Banner List</h4>
                            <a href="{{ route('admin.banner.create') }}" class="btn btn-primary">Add Data</a>
                        </div>
                        <div class="card-body">
                            <table class="table" id="data-notif">
                                <thead>
                                    <tr>
                                        <th>No</th>
                                        <th>Image</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--/ Basic table -->
    </div>

    @endsection

    @section('script')
    <!-- BEGIN: Page Vendor JS-->
    <script src="/backend/app-assets/vendors/js/tables/datatable/jquery.dataTables.min.js" defer></script>
    <script src="/backend/app-assets/vendors/js/tables/datatable/datatables.bootstrap4.min.js" defer></script>
    <script src="/backend/app-assets/vendors/js/tables/datatable/dataTables.responsive.min.js" defer></script>
    <script src="/backend/app-assets/vendors/js/tables/datatable/responsive.bootstrap4.js" defer></script>

    <script src="/backend/app-assets/js/scripts/tables/table-datatables-advanced.js" defer></script>
    <script src="/backend/app-assets/js/scripts/components/components-dropdowns.js"></script>
    <!-- END: Page Vendor JS-->
    <script src="https://cdn.ckeditor.com/4.16.1/standard/ckeditor.js"></script>
    <script>
    $(function(){
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });


        var table = $('#data-notif').DataTable({
            processing: true,
            serverSide: true,
            ajax: "/admin/banner",
            columns: [
            {
                data: null, "sortable": false,
                render: function (data, type, row, meta) { return meta.row + meta.settings._iDisplayStart + 1; },
            },
            {
                data    : 'image',
                render  : function (data , row ){
                    return `<img src="${data}" width="100">`
                }
            },        
            { data: 'title', name: 'title', title: 'Title' }, // Tambahkan kolom title
            { data: 'description', name: 'description', title: 'Description' },
            {
                data: 'id',
                render: (id) => /* html */`
                <div class="btn-group">
                    <button class="btn btn-flat-dark dropdown-toggle" type="button" id="dropdownMenuButton100" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <img src="/app-assets/images/align-justify.svg">
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="/admin/banner/edit/${id}">Edit</a>
                        <a class="dropdown-item" href="javascript:void(0);" onclick="return hapus(${id})">Hapus</a>
                    </div>
                </div>
                `
            },
            ],
            columnDefs: [
            {
                className: 'control',
                orderable: false,
                targets: 0
            }
            ],
            dom:
            '<"d-flex justify-content-between align-items-center mx-0 row"<"col-sm-12 col-md-6"l><"col-sm-12 col-md-6"f>>t<"d-flex justify-content-between mx-0 row"<"col-sm-12 col-md-6"i><"col-sm-12 col-md-6"p>>',
            orderCellsTop: true,
            responsive: {
                details: {
                    display: $.fn.dataTable.Responsive.display.modal({
                        header: function (row) {
                            var data = row.data();
                            return 'Details of ' + data['full_name'];
                        }
                    }),
                    type: 'column',
                    renderer: $.fn.dataTable.Responsive.renderer.tableAll({
                        tableClass: 'table'
                    })
                }
            },
            language: {
                paginate: {
                    // remove previous & next text from pagination
                    previous: '&nbsp;',
                    next: '&nbsp;'
                }
            },
            drawCallback: () => {
                $('.delete').click(function () {
                    const id = $(this).data(id)
                })
            }
        });
    });

    function hapus(id){
        var table = $('#data-notif').DataTable();
        clearToastObj = toastr['error'](
            'Are You Delete?<br /><br /><button type="button" class="btn btn-danger btn-sm delete">Yes</button>',
            'Deleted',
            {
                closeButton: true,
                timeOut: 0,
                extendedTimeOut: 0,
                tapToDismiss: false,
            }
            );

        if (clearToastObj.find('.delete').length) {
            clearToastObj.delegate('.delete', 'click', function () {
                toastr.clear(clearToastObj, { force: true });
                clearToastObj = undefined;
                $.ajax({
                    method: "GET",
                    url: "/admin/banner/delete/" + id,
                    success: function (data) {
                        toastr['success']('Successfully Delete Data.', 'Successfully', {
                            closeButton: true,
                            tapToDismiss: false,
                            progressBar: true,
                        });
                        table.ajax.reload();
                    },
                    error: function (data) {
                        toastr['success']('👋 Chocolate oat cake jelly oat cake candy jelly beans pastry.', 'Progress Bar', {
                            closeButton: true,
                            tapToDismiss: false,
                            progressBar: true,
                            rtl: isRtl
                        });
                    }
                });
            });
        }
    }
</script>
<script>
    $(function (){
        $('.hapus').on('click', function () {
            var id = $(this).attr('data-id');
            console.log(id);
        });
    });
</script>
    <script>
        CKEDITOR.replace( 'editor1' );
    </script>
    @if(Session::get('created'))
        <script type="text/javascript">
            $(document).ready(function(){
                toastr['success']('Successfully Create Data.', 'Successfully', {
                    closeButton: true,
                    tapToDismiss: false,
                    progressBar: true,
                });
            });
        </script>
    @endif

    @if(Session::get('updated'))
        <script type="text/javascript">
            $(document).ready(function(){
                toastr['success']('Successfully Update Data.', 'Successfully', {
                    closeButton: true,
                    tapToDismiss: false,
                    progressBar: true,
                });
            });
        </script>
    @endif
@endsection